---
- hosts: stake
  vars_prompt:
  - name: password
    prompt: "Enter validator password"

  tasks:
  - name: Install pip module pexpect
    become: yes
    pip:
      name: pexpect
      
  - name: Create validator account
    expect:
      command: /home/toni/prysm/prysm.sh validator accounts create
      responses:
        'Please specify the keystore path for your private keys \(default: \"/home/toni/\.eth2validators\"\):': "\n"
        'Enter a password': "{{ password }}"
        'Please re-enter your password': "{{ password }}"
      timeout: 180
    register: validator_output

  - name: Validator status output
    debug:
      var: validator_output
